#!/bin/sh

failed() {
    echo "TESTS FAILED!"
    exit 1
}

echo "=== test_unit ==="
nosetests3 --version || nose_missing=1
if [ -z "$nose_missing" ]; then
    nosetests3 -v || failed
fi

test_roundtrip() {
    echo "=== test_roundtrip ==="
    for f in tests/pseudoc-roundtrip/*.lst; do
        echo $f
        ./parse_asm.py --roundtrip --addr-width=2 --inst-indent=1 $f > $f.out || failed
        diff -u $f.exp $f.out || failed
    done
}

test_dump_c() {
    echo "=== test_dump_c ==="
    for f in tests/dump-c/*.lst; do
        echo $f
        ./dump_c.py $f > $f.out || failed
        diff -u $f.exp $f.out || failed
    done
}

test_xform() {
    echo "=== test_xform ==="
    for f in tests/*.lst; do
        echo $f
        ./apply_xform.py --debug --no-graph-header --format=none $f || failed
        diff -u $f.exp.bb $f.out.bb || failed
        if [ -f $f.exp.dot ]; then
            diff -u $f.exp.dot $f.out.dot || failed
        fi
    done
}

find tests -name '*.out*' -exec rm {} \;
test_roundtrip
test_dump_c
test_xform
echo "TESTS PASSED"
if [ -n "$nose_missing" ]; then
    echo
    echo "WARNING: unit tests were not run due to missing nosetests3 package"
fi
