// Estimated params: []
void fun_bfffb80f()
{
  // $a3 = 0x3feffe00; // {'uses': ['00000006', '00000012', '0000001b', '00000021', '00000041', '0000004a', '00000050', '00000059', '0000005f', '00000068', '00000073', '0000007c']} (dead);
  // memw(); (dead);
  // $a2 = *(u32*)0x3ff0000c; // {'uses': ['0000000c']} (dead);
  // $a4 = 0xeff; // {'uses': ['00000015']} (dead);
  while ((*(u32*)0x3ff0000c & BIT(8)) != 0) {
    // memw(); (dead);
    // $a6 = *(u32*)0x3ff0000c; // {'uses': ['00000015']} (dead);
    // $a6 = *(u32*)0x3ff0000c & 0xeff; // {'uses': ['0000001b']} (dead);
    // memw(); (dead);
    *(u32*)0x3ff0000c &= 0xeff; // {'uses': []}
    // memw(); (dead);
    // $a5 = *(u32*)0x3ff0000c; // {'uses': ['00000024']} (dead);
  }
  // $a5 = 0xfffdffff; // {'uses': ['00000036']} (dead);
  // $a7 = -0x2; // {'uses': ['00000044', '00000076']} (dead);
  // $a10 = 0x1; // {'uses': ['00000053']} (dead);
  // $a4 = 0x60000200; // {'uses': ['00000034', '0000003c']} (dead);
  // memw(); (dead);
  // $a2 = *(u32*)0x60000208; // {'uses': ['00000036']} (dead);
  // $a2 = *(u32*)0x60000208 & 0xfffdffff; // {'uses': ['0000003c']} (dead);
  // memw(); (dead);
  *(u32*)0x60000208 &= 0xfffdffff; // {'uses': []}
  // memw(); (dead);
  // $a11 = *(u32*)0x3ff0000c; // {'uses': ['00000044']} (dead);
  // $a11 = *(u32*)0x3ff0000c & 0xfffffffe; // {'uses': ['0000004a']} (dead);
  // memw(); (dead);
  *(u32*)0x3ff0000c &= 0xfffffffe; // {'uses': []}
  // memw(); (dead);
  // $a9 = *(u32*)0x3ff0000c; // {'uses': ['00000053']} (dead);
  // $a9 = *(u32*)0x3ff0000c | 0x1; // {'uses': ['00000059']} (dead);
  // memw(); (dead);
  *(u32*)0x3ff0000c |= 0x1; // {'uses': []}
  // memw(); (dead);
  // $a8 = *(u32*)0x3ff0000c; // {'uses': ['00000062']} (dead);
  while ((*(u32*)0x3ff0000c & BIT(1)) == 0) {
    // memw(); (dead);
    // $a6 = *(u32*)0x3ff0000c; // {'uses': ['0000006d']} (dead);
    nop();
  }
  // memw(); (dead);
  // $a8 = *(u32*)0x3ff0000c; // {'uses': ['00000076']} (dead);
  // $a8 = *(u32*)0x3ff0000c & 0xfffffffe; // {'uses': ['0000007c']} (dead);
  // memw(); (dead);
  *(u32*)0x3ff0000c &= 0xfffffffe; // {'uses': []}
}
