// Estimated params: []
void fun_bfff9567()
{
  // $a3 = 0x3ff20a00; // {'uses': ['00000006', '00000023', '0000002b', '00000034']} (dead);
  // memw(); (dead);
  // $a5 = *(u32*)0x3ff20de0; // {'uses': ['0000000c', '00000015']} (dead);
  // $a7 = 0x7f800000; // {'uses': ['0000000f']} (dead);
  // $a6 = *(u32*)0x3ff20de0 >> 1; // {'uses': ['0000000f']} (dead);
  // $a6 = *(u32*)0x3ff20de0 >> 1 & 0x7f800000; // {'uses': ['00000018']} (dead);
  // $a7 = 0xfc; // {'uses': ['00000015']} (dead);
  // $a5 = *(u32*)0x3ff20de0 & 0xfc; // {'uses': ['00000018']} (dead);
  // $a5 = *(u32*)0x3ff20de0 & 0xfc | *(u32*)0x3ff20de0 >> 1 & 0x7f800000; // {'uses': ['0000001d']} (dead);
  // $a6 = 0x3; // {'uses': ['0000001d']} (dead);
  $a5 = *(u32*)0x3ff20de0 & 0xfc | *(u32*)0x3ff20de0 >> 1 & 0x7f800000 | 0x3; // {'uses': ['00000023']}
  // memw(); (dead);
  *(u32*)0x3ff20de0 = $a5; // {'uses': []}
  // $a4 = -0x2; // {'uses': ['0000002e']} (dead);
  // memw(); (dead);
  // $a2 = *(u32*)0x3ff20c94; // {'uses': ['0000002e']} (dead);
  // $a2 = *(u32*)0x3ff20c94 & 0xfffffffe; // {'uses': ['00000034']} (dead);
  // memw(); (dead);
  *(u32*)0x3ff20c94 &= 0xfffffffe; // {'uses': []}
}
