name: Tests (pycopy)

on:
  push:
  # Manual trigger from UI, https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v1
    - name: Install pycopy
      run: |
        mkdir -p ~/bin
        echo "~/bin" >> $GITHUB_PATH
        wget -q https://github.com/pfalcon/pycopy/releases/download/v3.6.1/pycopy-v3.6.1-bin.tar.gz
        tar -xzf pycopy-v3.6.1-bin.tar.gz -C ~/bin/
    - name: Pycopy version
      run: |
        pycopy-dev -c 'import sys; print(sys.implementation)'
    - name: Install requirements
      run: |
        pycopy-dev -m upip install -r requirements-pycopy.txt
    - name: Run testsuite
      run: |
        PYTHON="pycopy-dev -X strict" ./run_tests
